---
# amazon linux
- name: import zabbix rpm key
  rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: create yum repo 
  template: dest=/etc/yum.repos.d/zabbix.repo src=yum.repo.j2 owner=root mode=0644

- name: install httpd24
  yum: name={{ item }} state=present  # default on 2014.09
  with_items:
    - httpd24
    - httpd24-tools
    - mod24_ssl


- name: start http
  service: name=httpd state=started enabled=yes

- name: install mysql
  yum: name=mysql-server state=present

- name: start mysql
  service: name=mysqld state=started enabled=yes

- name: install python mysql driver
  yum: name=MySQL-python state=present

- name: create mysql database for zabbix
  mysql_db: name={{ ansible_zabbix_server_db_name }} state=present

- name: create mysql user for zabbix
  mysql_user: name={{ ansible_zabbix_server_db_name }} 
        password={{ ansible_zabbix_server_db_password }} 
        priv={{ ansible_zabbix_server_db_name }}.*:ALL 
        state=present

- name: install zabbix server package
  yum: name=zabbix-server-{{ zabbix_server_type }}

- name: install zabbix server front end
  yum: name=zabbix-web-{{ zabbix_server_type }}

- name: start zabbix server
  service: name=zabbix-server state=started enabled=yes

- name: configure zabbix server 
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
  notify:
    - restart zabbix server

- name: php time zone
  lineinfile: dest=/etc/php.ini state=present line='date.timezone="{{ ansible_zabbix_server_timezone }}"  ; changed by Ansible' 
  notify:
    - restart httpd

- name: upgrade apache 2.4  # http://httpd.apache.org/docs/2.4/upgrading.html
  template: src=zabbix_server_httpd24.j2 dest=/etc/httpd/conf.d/zabbix.conf
  notify:
    - restart httpd
