---
# ubuntu specific
#
- name: update apt
  raw: "apt-get update"

- name: fetch zabbix repo
  get_url: url=http://repo.zabbix.com/zabbix/2.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.0-1precise_all.deb dest=/tmp/zabbix-release_2.0-1precise_all.deb mode=600

- name: install zabbix repo
  apt: deb=/tmp/zabbix-release_2.0-1precise_all.deb update_cache=True

- name: install zabbix server
  apt: pkg={{ item }} state=latest
  with_items:
    - zabbix-agent
    - zabbix-frontend-php
    - zabbix-server-mysql

- name: percona repo key
  apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A

- name: percona repo bin 
  apt_repository: repo='deb http://repo.percona.com/apt precise main' state=present update_cache=True

- name: percona repo src
  apt_repository: repo='deb-src http://repo.percona.com/apt precise main' state=present update_cache=True

- name: install percona agent utils
  apt: pkg=percona-zabbix-templates state=latest
